#************************************************************************** */
#                                                                           */
#                                                       :::      ::::::::   */
#  docker-compose.yml                                 :+:      :+:    :+:   */
#                                                   +:+ +:+         +:+     */
#  By:castorga <castorga@student.42barcelona.com> +#+  +:+       +#+        */
#                                               +#+#+#+#+#+   +#+           */
#  Created: 2025/03/10 17:30:00 by castorga          #+#    #+#             */
#  Updated: 2025/03/21 17:30:00 by castorga         ###   ########.fr       */
#                                                                           */
#************************************************************************** */

# ------- mandatory -------
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    restart: always
    volumes:
      - wp_castor_vol:/var/www/html
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - networkcastorga

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    restart: always
    volumes:
      - wp_castor_vol:/var/www/html
    env_file:
      - .env
    networks:
      - networkcastorga

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    restart: always
    volumes:
      - db_castor_vol:/var/lib/mysql
    env_file:
      - .env
    networks:
      - networkcastorga
  
  static-website:
    container_name:  static-website
    build: ./requirements/static-website
    ports:
      - "80:80"

volumes:
  db_castor_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind

  wp_castor_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind


networks:
  networkcastorga:
    driver: bridge
    name: networkcastorga