services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    restart: always
    volumes:
      - wordpress_vol:/var/www/html
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - networkcastorga

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    restart: always
    volumes:
      - wordpress_vol:/var/www/html
    env_file:
      - .env
    networks:
      - networkcastorga

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    restart: always
    volumes:
      - mariadb_vol:/var/lib/mysql
    env_file:
      - .env
    networks:
      - networkcastorga

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/castorga/data/mariadb
      o: bind

  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/castorga/data/wordpress
      o: bind

networks:
  networkcastorga:
    driver: bridge
    name: networkcastorga