
#_docker-compose.yml                                                

networks:
    castorganet:
        name: castorganet
        driver: bridge

services:
    nginx:
        container_name: nginx
        image: nginx
        ports:
         - 443:443
        volumes:
         - wordpress_data:/var/www/html
        restart: always
        networks:
         - castorganet


    mariadb:
         container_name: mariadb
         build:
            context: ./requirements/mariadb
         volumes:
          - mariadb_data:/var/lib/mysql
         restart: always
         networks:
          - castorganet
         env_file:
          - .env

    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        depends_on:
         - mariadb
        volumes:
         - wordpress_data:/var/www/html
        restart: always
        networks:
         - castorganet
        env_file:
          - .env

volumes:
    mariadb_data:
        driver: local
        driver_opts:
            type: none
            device: /home/castorga/data/mysql
            o: bind

    wordpress_data:
        driver: local
        driver_opts:
            type: none
            device: /home/castorga/data/wordpress
            o: bind
